export const storeData = [
  {
    type: "Mac",
    name: "MacBook Air avec puce M1",
    prix: "A partir de 1 199 €",
    screen: "Écran Retina de 13.3 pouces",
    puce: "Puce Apple M1",
    RAM: "8 Go ou 16 Go de mémoire unifiée",
    stockage: "256 Go à 2 To de stockage",
    autonomie: "jusqu'à 18 heures d'autonomie",
    gadgets: "Touch ID",
    dimensions: {
      Hauteur: "0.41 à 1.61 cm",
      Largeur: "30.41cm",
      Profondeur: "21.24cm",
      Poids: "1.29 kg",
    },
    exploitation: "macOS",
  },
  {
    type: "Mac",
    name: 'MacBook Pro 13"',
    prix: "A partir de 1 599 €",
    screen: "Écran Retina de 13.3 pouces",
    puce: "Puce Apple M2",
    RAM: "8 Go à 24 Go de mémoire unifiée",
    stockage: "256 Go à 2 To de stockage",
    autonomie: "jusqu'à 20 heures d'autonomie",
    gadgets: "Touch ID , Touch Bar",
    dimensions: {
      Hauteur: "1.56cm",
      Largeur: "30.41cm",
      Profondeur: "21.24cm",
      Poids: "1.4 kg",
    },
    exploitation: "macOS",
  },
  {
    type: "IPhone",
    name: 'Iphone 13"',
    prix: "A partir de 809 €",
    screen: "Écran Super Retina XTR de 6.1 ou 5.4 pouces",
    puce: "Puce A15 Bionic avec GPU 4 coeurs",
    RAM: "8 Go à 24 Go de mémoire unifiée",
    stockage: "128 Go à 512 Go de stockage",
    autonomie: "jusqu'à 19 heures d'autonomie",
    gadgets: "Face ID , 5G",
    dimensions: {
      Hauteur: "146.7 mm",
      Largeur: "71.5 mm",
      Profondeur: "7.65 mm",
      Poids: "173 g",
    },
    exploitation: "IOS",
  },
  {
    type: "IPhone",
    name: 'Iphone 14"',
    prix: "A partir de 1019 €",
    screen:
      "Écran Super Retina XDR Technologie ProMotion Écran toujours activé de 6.7 ou 6.1 pouces",
    puce: "Puce A16 Bionic",
    RAM: "8 Go à 24 Go de mémoire unifiée",
    stockage: "128 Go à 512 Go de stockage",
    autonomie: "jusqu'à 29 heures d'autonomie",
    gadgets: "Face ID , 5G",
    dimensions: {
      Hauteur: "146.7 mm",
      Largeur: "71.5 mm",
      Profondeur: "7.8 mm",
      Poids: "172 g",
    },
    exploitation: "IOS",
  },
  {
    type: "IPad",
    name: "Ipad Air",
    prix: "A partir de 789 €",
    screen: "10.9 pouces",
    puce: "Puce Apple M1",
    RAM: "8 Go ",
    stockage: "64 Go à 256 Go de stockage",
    autonomie: "jusqu'à 10 heures d'autonomie",
    dimensions: {
      Hauteur: "247.6 mm",
      Largeur: "178.5 mm",
      Profondeur: "6.1 mm",
      Poids: "461 g",
    },
    exploitation: "IPadOS 16",
  },
  {
    type: "IPad",
    name: "Ipad Air",
    prix: "A partir de 589 €",
    screen: "10.9 pouces",
    puce: "Puce A14 Bionic",
    RAM: "8 Go ",
    stockage: "64 Go à 256 Go de stockage",
    autonomie: "jusqu'à 10 heures d'autonomie",
    dimensions: {
      Hauteur: "248.6 mm",
      Largeur: "179.5 mm",
      Profondeur: "7 mm",
      Poids: "481 g",
    },
    exploitation: "IPadOS 16",
  },
];
